body:
  - type: passwordBox
    attributes:
      name: api_key
      label: "API Key:"
      defaultValue: ""
      description: OpenAI API Key
  - type: dropdown
    attributes:
      name: model
      label: "Model:"
      defaultValue: gpt-3.5-turbo
      options:
        - gpt-3.5-turbo
        - gpt-4
        - gpt-4-0125-preview
        - gpt-4-turbo-preview
        - gpt-4-1106-preview
        - gpt-4-0613
        - gpt-4o
        - gpt-4o-mini
  - type: input
    attributes:
      name: prompt_stop
      label: "Prompt stop:"
      defaultValue: "||"
      description: Characters to indicate end of prompt
  - type: input
    attributes:
      name: default_prompt
      label: "Default system prompt:"
      defaultValue: "normal"
      description: Default key word that will be looked up in the system_messages.csv file
  - type: checkbox
    attributes:
      name: save_conversation
      label: 'Save conversation:'
      defaultValue: "false"
      description: Check to save the conversations for each prompt type in a .txt file in the plugin folder
  - type: dropdown
    attributes:
      name: log_level
      label: "Log Level:"
      defaultValue: error
      options:
        - info
        - debug
        - warning
        - error
        - critical
  - type: input
    attributes:
      name: api_endpoint
      label: "API Endpoint:"
      defaultValue: "https://api.openai.com/v1/chat/completions"
      description: Custom OpenAI API endpoint
